@SinyakinAS Task1. Variant 2 Version 1
MariaKocheganova/IiP_381908_2_2 pull request #1
Opened 2020-02-26 18:48 UTC by SinyakinAS

2020-02-27 09:46 UTC, MariaKocheganova commented on sinyakin.as/Task1/Source1.cpp
> +		str[len] = 0;
Признак конца строки должен быть положен в строку один раз вне цикла.

2020-02-27 09:49 UTC, MariaKocheganova commented on sinyakin.as/Task1/Source1.cpp
> +	size = string.GetSize();
Работать будет. Однако, чтобы привыкать в дальнейшем к правильному обращению к полям класса внутри методов класса, все-такие поправьте на непосредственное обращение к полям, не через функции Get. А для аргумента поставьте спецификатор const.

2020-02-27 09:51 UTC, MariaKocheganova commented on sinyakin.as/Task1/Source1.cpp
> +	delete(str);
Здесь вы сначала занулили указатель, а потом попытались вызвать освобождение памяти, на которую уже никто не ссылается. Это ошибка.

2020-03-04 16:29 UTC, MariaKocheganova requested changes

2020-03-04 16:29 UTC, MariaKocheganova commented on sinyakin.as/Task1/Source1.cpp
> +		return *this;
return не должен находиться в цикле

2020-03-04 16:29 UTC, MariaKocheganova commented on sinyakin.as/Task1/Source1.cpp
> +		len = s.len;
сейчас size и len у вас обновляются только в условном операторе if. В случае, если if не сработает, объект проинициализируется неверно

2020-03-04 16:29 UTC, MariaKocheganova commented on sinyakin.as/Task1/Source1.cpp
> +	res.len = len + s.len;
Где заполняется res.size?

2020-03-04 16:29 UTC, MariaKocheganova commented on sinyakin.as/Task1/Source1.cpp
> +	if (size < len + s.len)
Проверьте условие, забыли конец строки

2020-03-16 11:08 UTC, MariaKocheganova approved these changes
Отсутствует реализация конструктора преобразования из строки и метод представления даты в виде строки.
Комментарии об операторе сложения переносятся и для оператора вычитания.

2020-03-16 11:08 UTC, MariaKocheganova commented on sinyakin.as/Task0/Header1.h
> +	Date& operator+(int j);
Операторы сложения и вычитания возвращаемое значение передают не по ссылке, а по значению.

2020-03-16 11:08 UTC, MariaKocheganova commented on sinyakin.as/Task0/Source1.cpp
> +	Day = i;
Контроль входного значения должен происходить внутри конструктора, а не вне.

2020-03-16 11:08 UTC, MariaKocheganova commented on sinyakin.as/Task0/Source1.cpp
> +	cout << "Enter a number of days you wanna add to your recent date - ";
Количество суток, которое вы должны прибавить передается через аргумент! Его не нужно вводить дополнительно, иначе не понятен смысл оператора.

2020-03-16 11:08 UTC, MariaKocheganova commented on sinyakin.as/Task0/Source1.cpp
> +	cout << "The new brand new date is -  " << endl;
Вы перегружаете оператор сложения. Представьте, что вы вызываете сложение двух чисел типа int,  и в процессе сложения что-то выводится на экран. Это не то, что мы ожидаем. Никакого ввода и вывода внутри стандартных операторов быть не должно.

2020-03-16 11:08 UTC, MariaKocheganova commented on sinyakin.as/Task0/Source1.cpp
> +		for (m = 0; m < 13; m++)
У вас повторяется фрагмент кода внутри if и внутри else. Это признак того, что код можно (и нужно) перестроить. Например в цикле сначала убрать необходимое количество лет (которое, к слову, может быть больше 1).

2020-03-16 11:08 UTC, MariaKocheganova commented on sinyakin.as/Task0/Main.cpp
> +		a.operator-(j);
Технически запись верная. Но мы ей не пользуемся. Мы перегружаем операторы, чтобы можно было их вызывать в привычном виде: a= a, a = a - 8, a+12345 и т.д.

2020-03-16 11:08 UTC, MariaKocheganova commented on sinyakin.as/Task0/Main.cpp
> +	if (i <= 31 && j <= 12 && k > 0)
Неясно, зачем нужна эта проверка на данном этапе.

2020-03-28 16:28 UTC, MariaKocheganova requested changes
Вижу, что работа идет. Обратите внимание на комментарии и исправьте их. Если будут вопросы, задавайте.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task0/Source1.cpp
> +	int i3 = std::stoi(s3);
Неправильно используете функцию assign. Уточните, что означают ее аргументы и используйте верно.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task0/Main.cpp
> +	Date d11(s);
Ваша программа main не тестирует ни одного оператора, не выводит на экран ни одного из созданных объектов. Поэтому нет никакой уверенности в правильности вашего кода.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task0/Source1.cpp
> +		if (res.Day > 30)
Какой смысл здесь несет условный оператор if, если вы только что строчкой выше написали while на то же условие?
То же относится и к оператору вычитания.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task2/Source1.cpp
> +		number[i] = '0';
Вы выделили память размером 1000*sizef(char), не освободили ее, и уже никогда не сможете ей воспользоваться. Это ошибка работы с памятью.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task2/Source1.cpp
> +	char* number = new char[s];
Тот же комментарий: number вы объявили как локальную переменную. Это не поле класса, это динамический массив, доступ к элементам которого пропадает как только вы выйдете из данного конструктора. Память нужно было выделять под hex.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task2/Source1.cpp
> +	hex = B.hex;
Когда нам нужно скопировать указатели, то мы 1) выделяем память под новый массив и 2) поэлементно копируем его содержимое.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task2/Source1.cpp
> +	}
в этом цикле не меняется переменная A_copy. Это значит, что один раз попав в тело цикла, вы уже никогда из него не выйдете -> программа зависнет, попав в бесконечный цикл.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task2/Source1.cpp
> +		A_copy / 10;
Вы поделили на 10, но забыли запомнить результат этого деления. -> A_copy снова не меняется в цикле.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task2/Source1.cpp
> +		hex[i] = (A_copy % 16);
Вы должны в массив положить символ, а не код символа, как делаете это сейчас. То есть если в результате взятия остатка получилось 9, то в hex[i] должно оказаться '9', а не 9.

2020-03-28 16:28 UTC, MariaKocheganova commented on sinyakin.as/Task2/Source1.cpp
> +	return *this;
Вот это правильное копирование указателей! (см.комментарий к строке 23)

2020-05-27 13:02 UTC, SinyakinAS commented
Простите за мою некомпетентность. Проверьте пожалуйста.

2020-05-28 18:48 UTC, merged